-- V2__insert_all_countries.sql
INSERT INTO countries (iso2, iso3, country_name, flag) VALUES
                                                           ('AF', 'AFG', 'Afghanistan', '🇦🇫'),
                                                           ('AL', 'ALB', 'Albania', '🇦🇱'),
                                                           ('DZ', 'DZA', 'Algeria', '🇩🇿'),
                                                           ('AD', 'AND', 'Andorra', '🇦🇩'),
                                                           ('AO', 'AGO', 'Angola', '🇦🇴'),
                                                           ('AR', 'ARG', 'Argentina', '🇦🇷'),
                                                           ('AM', 'ARM', 'Armenia', '🇦🇲'),
                                                           ('AU', 'AUS', 'Australia', '🇦🇺'),
                                                           ('AT', 'AUT', 'Austria', '🇦🇹'),
                                                           ('AZ', 'AZE', 'Azerbaijan', '🇦🇿'),
                                                           ('BH', 'BHR', 'Bahrain', '🇧🇭'),
                                                           ('BD', 'BGD', 'Bangladesh', '🇧🇩'),
                                                           ('BY', 'BLR', 'Belarus', '🇧🇾'),
                                                           ('BE', 'BEL', 'Belgium', '🇧🇪'),
                                                           ('BA', 'BIH', 'Bosnia and Herzegovina', '🇧🇦'),
                                                           ('BR', 'BRA', 'Brazil', '🇧🇷'),
                                                           ('BG', 'BGR', 'Bulgaria', '🇧🇬'),
                                                           ('CA', 'CAN', 'Canada', '🇨🇦'),
                                                           ('CL', 'CHL', 'Chile', '🇨🇱'),
                                                           ('CN', 'CHN', 'China', '🇨🇳'),
                                                           ('CO', 'COL', 'Colombia', '🇨🇴'),
                                                           ('HR', 'HRV', 'Croatia', '🇭🇷'),
                                                           ('CU', 'CUB', 'Cuba', '🇨🇺'),
                                                           ('CY', 'CYP', 'Cyprus', '🇨🇾'),
                                                           ('CZ', 'CZE', 'Czech Republic', '🇨🇿'),
                                                           ('DK', 'DNK', 'Denmark', '🇩🇰'),
                                                           ('DO', 'DOM', 'Dominican Republic', '🇩🇴'),
                                                           ('EC', 'ECU', 'Ecuador', '🇪🇨'),
                                                           ('EG', 'EGY', 'Egypt', '🇪🇬'),
                                                           ('EE', 'EST', 'Estonia', '🇪🇪'),
                                                           ('FI', 'FIN', 'Finland', '🇫🇮'),
                                                           ('FR', 'FRA', 'France', '🇫🇷'),
                                                           ('DE', 'DEU', 'Germany', '🇩🇪'),
                                                           ('GR', 'GRC', 'Greece', '🇬🇷'),
                                                           ('HU', 'HUN', 'Hungary', '🇭🇺'),
                                                           ('IN', 'IND', 'India', '🇮🇳'),
                                                           ('ID', 'IDN', 'Indonesia', '🇮🇩'),
                                                           ('IR', 'IRN', 'Iran', '🇮🇷'),
                                                           ('IQ', 'IRQ', 'Iraq', '🇮🇶'),
                                                           ('IE', 'IRL', 'Ireland', '🇮🇪'),
                                                           ('IL', 'ISR', 'Israel', '🇮🇱'),
                                                           ('IT', 'ITA', 'Italy', '🇮🇹'),
                                                           ('JP', 'JPN', 'Japan', '🇯🇵'),
                                                           ('JO', 'JOR', 'Jordan', '🇯🇴'),
                                                           ('KZ', 'KAZ', 'Kazakhstan', '🇰🇿'),
                                                           ('KE', 'KEN', 'Kenya', '🇰🇪'),
                                                           ('KR', 'KOR', 'South Korea', '🇰🇷'),
                                                           ('KW', 'KWT', 'Kuwait', '🇰🇼'),
                                                           ('LV', 'LVA', 'Latvia', '🇱🇻'),
                                                           ('LB', 'LBN', 'Lebanon', '🇱🇧'),
                                                           ('LY', 'LBY', 'Libya', '🇱🇾'),
                                                           ('LT', 'LTU', 'Lithuania', '🇱🇹'),
                                                           ('LU', 'LUX', 'Luxembourg', '🇱🇺'),
                                                           ('MK', 'MKD', 'North Macedonia', '🇲🇰'),
                                                           ('MY', 'MYS', 'Malaysia', '🇲🇾'),
                                                           ('MT', 'MLT', 'Malta', '🇲🇹'),
                                                           ('MX', 'MEX', 'Mexico', '🇲🇽'),
                                                           ('MD', 'MDA', 'Moldova', '🇲🇩'),
                                                           ('ME', 'MNE', 'Montenegro', '🇲🇪'),
                                                           ('MA', 'MAR', 'Morocco', '🇲🇦'),
                                                           ('NL', 'NLD', 'Netherlands', '🇳🇱'),
                                                           ('NZ', 'NZL', 'New Zealand', '🇳🇿'),
                                                           ('NG', 'NGA', 'Nigeria', '🇳🇬'),
                                                           ('NO', 'NOR', 'Norway', '🇳🇴'),
                                                           ('PK', 'PAK', 'Pakistan', '🇵🇰'),
                                                           ('PL', 'POL', 'Poland', '🇵🇱'),
                                                           ('PT', 'PRT', 'Portugal', '🇵🇹'),
                                                           ('RO', 'ROU', 'Romania', '🇷🇴'),
                                                           ('RU', 'RUS', 'Russia', '🇷🇺'),
                                                           ('SA', 'SAU', 'Saudi Arabia', '🇸🇦'),
                                                           ('RS', 'SRB', 'Serbia', '🇷🇸'),
                                                           ('SG', 'SGP', 'Singapore', '🇸🇬'),
                                                           ('SK', 'SVK', 'Slovakia', '🇸🇰'),
                                                           ('SI', 'SVN', 'Slovenia', '🇸🇮'),
                                                           ('ZA', 'ZAF', 'South Africa', '🇿🇦'),
                                                           ('ES', 'ESP', 'Spain', '🇪🇸'),
                                                           ('SE', 'SWE', 'Sweden', '🇸🇪'),
                                                           ('CH', 'CHE', 'Switzerland', '🇨🇭'),
                                                           ('TH', 'THA', 'Thailand', '🇹🇭'),
                                                           ('TR', 'TUR', 'Turkey', '🇹🇷'),
                                                           ('UA', 'UKR', 'Ukraine', '🇺🇦'),
                                                           ('AE', 'ARE', 'United Arab Emirates', '🇦🇪'),
                                                           ('GB', 'GBR', 'United Kingdom', '🇬🇧'),
                                                           ('US', 'USA', 'United States', '🇺🇸'),
                                                           ('VN', 'VNM', 'Vietnam', '🇻🇳');
